# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Fotografía"
subtitle: ""
author:  "JapeBape"
header:
 title: "Fotografía"
 subtitle: "JapeBape"
footer:
 name: ""
 bio: ""
social_urls:
#  twitter: "https://twitter.com/pushpinderpal_"
  instagram: "https://www.instagram.com/jape.raw/"
#  linkedin: "https://www.linkedin.com/in/pushpinderpalsingh/"
#  github: ""
